### ISSUE TITLE
CompVMathOpSubSubMul_32f32f32f_Asm_X64_AVX requires AVX2

### ISSUE THREAD

**Issue by george-hopkins** [DoubangoTelecom/CompV#175]
`CompVMathOpSubSubMul_32f32f32f_Asm_X64_AVX` uses `vbroadcastss ymm0, xmm0` which has been introduced in AVX2. In `CompVMathOpSubSubMul` the aforementioned implementation is chosen even if the CPU only supports AVX. This causes an exception (illegal instruction) at runtime.

**Comment by DoubangoTelecom** [comment]
Replaced "VBROADCASTSS ymm1, xmm2" (AVX2) with "BROADCASTSS ymm1, m32" (AVX). Source: https://www.felixcloutier.com/x86/vbroadcast. Will take time to reach other projects using the lib (UltimateALPR, FaceLiveness...)
